version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - uname -r
      - yum -y install python3-devel cmake3
    finally:
      - echo This always runs even if the install command fails
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - export PLX_SDK_DIR=${CODEBUILD_SRC_DIR_plx}
      - export PLX_CHIP=9054
      - make -C ${PLX_SDK_DIR}/PlxApi/ PLX_NO_CLEAR_SCREEN=1
      - if [ ! -f ${PLX_SDK_DIR}/PlxApi/Library/PlxApi.a ];then echo "PLX Static lib missing!"; exit 1; fi
      - if [ ! -f ${PLX_SDK_DIR}/PlxApi/Library/PlxApi.so ];then echo "PLX SO lib missing!"; exit 1; fi
    finally:
      - echo This always runs even if the pre_build command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mkdir build
      - cd build
      - cmake3 ../
      - make -j4
      - ./tests/unit/legacy/legacy_unit_test_runner
      - ./tests/unit/sdk/pixie_sdk_unit_test_runner
      - ./tests/integration/pixie_sdk_integration_test_runner
    finally:
      - echo This always runs even if the build command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`